"use strict";
// Generates Sim/CostPow.lua: the reference profile's Math.pow results at integer
// bases (phase-two building costs, probe trust and rates), where they differ from Sim/JSMath.lua's correctly
// rounded pow. V8 13.6 calls the platform C library's pow (--use-std-math-pow
// defaults to true), so these results belong to the pinned profile below, not to
// every browser. Every integer base in each domain is compared; beyond a domain
// the simulation uses JSMath.pow, a declared difference (#24,
// docs/reference/WORKSHOP.md).
//   node tests/reference/cost_pow.cjs          check (exit 1 when stale)
//   node tests/reference/cost_pow.cjs --write  regenerate
const fs=require("node:fs"), path=require("node:path"), os=require("node:os");
const {spawnSync}=require("node:child_process");
const {LUA,exactParts}=require("./workshop.cjs");

const ROOT=path.resolve(__dirname,"../..");
const OUTPUT=path.join(ROOT,"Sim/CostPow.lua");
// Exponent -> largest integer base (level + 1, including the 10/100/1000 price
// lookahead) the slice supports. main.js: drones 2.25, batteries 2.54, farms 2.78;
// probes: drift Math.pow(probeTrust, 1.2), trust cost 1.47, hazards Math.pow(probeHaz, 1.6).
const DOMAINS=[[2.25,200000],[2.54,30000],[2.78,30000],[1.2,10000],[1.47,10000],[1.6,10000]];
const PROFILE={node:process.version,v8:process.versions.v8,platform:process.platform,arch:process.arch};

const text=v=>exactParts(v).join(":");
const parse=s=>{const [m,e]=s.split(":").map(Number);return m*2**e;};
function words(v) {
    const view=new DataView(new ArrayBuffer(8));
    view.setFloat64(0,v);
    const hex=n=>"0x"+n.toString(16).toUpperCase().padStart(8,"0");
    return "{ "+hex(view.getUint32(0))+", "+hex(view.getUint32(4))+" }";
}

// Lua's JSMath.pow for every base in every domain.
function luaPow() {
    const dir=fs.mkdtempSync(path.join(os.tmpdir(),"tim-costpow-"));
    try {
        const input=path.join(dir,"cases.txt"), output=path.join(dir,"results.txt"), lines=[];
        for (const [e,limit] of DOMAINS) for (let n=1;n<=limit;n++) lines.push("pow "+text(n)+" "+text(e));
        fs.writeFileSync(input,lines.join("\n")+"\n");
        const run=spawnSync(LUA,[path.join(__dirname,"lua_math_probe.lua"),input,output],{encoding:"utf8"});
        if (run.status!==0) throw new Error("Lua pow probe failed: "+run.stderr);
        return fs.readFileSync(output,"utf8").trim().split(/\r?\n/).map(parse);
    } finally { fs.rmSync(dir,{recursive:true,force:true}); }
}

function generate() {
    const lua=luaPow(), out=[
        "-- Generated by tests/reference/cost_pow.cjs; do not edit. The reference",
        "-- profile's Math.pow(n, e) at integer bases (building costs, probe formulas) where it differs",
        "-- from JSMath.pow (correctly rounded). Every integer base 1..limit was compared.",
        "-- Profile: Node "+PROFILE.node+", V8 "+PROFILE.v8+", "+PROFILE.platform+" "+PROFILE.arch+
            " (V8 calls the platform pow).",
        "-- Values are IEEE {high, low} words.",
        "local _, ns = ...",
        "ns = ns or {}",
        "ns.CostPow = {",
        "  profile = "+JSON.stringify(PROFILE.node+" V8 "+PROFILE.v8+" "+PROFILE.platform+" "+PROFILE.arch)+",",
    ];
    let i=0;
    for (const [e,limit] of DOMAINS) {
        const fixes=[];
        for (let n=1;n<=limit;n++,i++) {
            const v8=Math.pow(n,e);
            if (lua[i]!==v8) fixes.push("    ["+n+"] = "+words(v8)+",");
        }
        out.push("  ["+JSON.stringify(String(e))+"] = { limit = "+limit+", fixes = {",...fixes,"  } },");
    }
    out.push("}","return ns.CostPow","");
    return out.join("\n");
}

module.exports={OUTPUT,DOMAINS,PROFILE,generate};

if (require.main===module) {
    const text=generate();
    if (process.argv.includes("--write")) { fs.writeFileSync(OUTPUT,text); console.log("wrote",OUTPUT); }
    else if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT,"utf8")!==text) { console.log("stale:",OUTPUT); process.exitCode=1; }
    else console.log("current:",OUTPUT);
}
