"use strict";
// Generates docs/reference/PROJECTS.md: all 96 reference projects in registration
// order with their port status, from the committed inventory and the Lua
// project table. node tests/reference/project_checklist.cjs --write updates it.
const fs=require("node:fs"), path=require("node:path"), {spawnSync}=require("node:child_process");
const ROOT=path.resolve(__dirname,"../.."), OUTPUT=path.join(ROOT,"docs/reference/PROJECTS.md");
const LUA=process.env.TIM_LUA || "C:/Program Files (x86)/Lua/5.1/lua.exe";

function portedProjects() {
    const script=[
        'local ns = {}',
        'assert(loadfile("Sim/Reference.lua"))("TimeIsMoney", ns)',
        'for _, path in ipairs(ns.Reference.files) do assert(loadfile(path))("TimeIsMoney", ns) end',
        'for _, entry in ipairs(ns.Workshop.projects) do io.write(entry.name, "\\t", entry.stop or "", "\\n") end',
    ].join("\n");
    const out=spawnSync(LUA,["-e",script],{cwd:ROOT,encoding:"utf8"});
    if (out.status!==0) throw new Error("Lua project listing failed: "+out.stderr);
    return new Map(out.stdout.trim().split(/\r?\n/).map(line=>line.split("\t")));
}

// The traces that buy each project: { [trace] = [project names] } from the Lua
// runner's purchase report. Only traces that match the reference with no error
// count. workshop.test.cjs passes the comparisons it already made (and asserts
// them); the command line compares every trace itself (about ten minutes).
function tracePurchases() {
    const Workshop=require("./workshop.cjs"), bought={};
    for (const name of Workshop.names) {
        const {port,divergence}=Workshop.compare(name);
        if (divergence || port.error) throw new Error("trace "+name+" does not match the reference; fix it first");
        bought[name]=port.purchases;
    }
    return bought;
}
// project200/201/217 end the company: the reference resets and reloads, which its
// host cannot trace. These Lua tests cover their effects and the restart (#23).
// workshop.test.cjs checks that each named file clicks or runs the project's button.
const RESTARTS={project200:["test_sim.lua","test_host.lua"], project201:["test_host.lua"],
    project217:["test_sim.lua","test_host.lua","test_restart.lua"]};

function generate(purchases=tracePurchases()) {
    const byProject=new Map();
    for (const [trace,names] of Object.entries(purchases))
        for (const name of names) byProject.set(name,[...(byProject.get(name)||[]),trace]);
    const inventory=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/reference/inventory.json"),"utf8"));
    const source=inventory.sources["projects.js"];
    const byName=new Map(source.projects.map(p=>[p.name,p]));
    const ported=portedProjects();
    const rows=source.project_registration_order.map((name,index)=>{
        const project=byName.get(name);
        let status;
        if (ported.has(name)) {
            const stop=ported.get(name);
            status=stop ? `trigger and eligibility; purchase stops (${stop})` : "trigger, eligibility and purchase effect";
        } else {
            status="later slice: its trigger needs the endings";
        }
        const traces=byProject.get(name)||[];
        const where=traces.length ? traces.slice(0,3).join(", ")+(traces.length>3 ? ` (+${traces.length-3})` : "")
            : (RESTARTS[name] ? "restart: "+RESTARTS[name].join(", ") : "**none**");
        return `| ${index+1} | ${name} | ${project.fields.id.initial} | ${project.line} | ${status} | ${where} |`;
    });
    const counted=[...ported.values()];
    return [
        "# Project traceability",
        "",
        "Generated by tests/reference/project_checklist.cjs from",
        "[inventory.json](inventory.json) and Sim/Projects.lua; do not edit by hand.",
        "workshop.test.cjs checks that this file is current.",
        "",
        "*Bought in* names the differential traces (tests/reference/workshop.cjs) in",
        "which the project's purchase effect runs; each of them matches the reference",
        "at every checkpoint. The restarts end the company and are covered by the Lua",
        "tests named instead.",
        "",
        `All three phases and the endings port ${counted.filter(s=>!s).length} purchase effects and`,
        `${counted.filter(s=>s).length} explicit purchase stops. The restarts (the prestige routes and Quantum`,
        `Temporal Reversion) end the company; the host starts the next one (#23).`,
        "",
        "| # | Project | Button | projects.js line | Port | Bought in |",
        "| ---: | --- | --- | ---: | --- | --- |",
        ...rows,
        "",
    ].join("\n");
}
module.exports={generate,OUTPUT,RESTARTS};

if (require.main===module) {
    const text=generate();
    if (process.argv.includes("--write")) fs.writeFileSync(OUTPUT,text);
    else process.stdout.write(text);
}
