"use strict";
// Generates docs/reference/PROJECTS.md: all 96 reference projects in registration
// order with their port status, from the committed inventory and the Lua
// project table. node tests/reference/project_checklist.cjs --write updates it.
const fs=require("node:fs"), path=require("node:path"), {spawnSync}=require("node:child_process");
const ROOT=path.resolve(__dirname,"../.."), OUTPUT=path.join(ROOT,"docs/reference/PROJECTS.md");
const LUA=process.env.TIM_LUA || "C:/Program Files (x86)/Lua/5.1/lua.exe";

function portedProjects() {
    const script=[
        'local ns = {}',
        'assert(loadfile("Sim/Reference.lua"))("TimeIsMoney", ns)',
        'for _, path in ipairs(ns.Reference.files) do assert(loadfile(path))("TimeIsMoney", ns) end',
        'for _, entry in ipairs(ns.Workshop.projects) do io.write(entry.name, "\\t", entry.stop or "", "\\n") end',
    ].join("\n");
    const out=spawnSync(LUA,["-e",script],{cwd:ROOT,encoding:"utf8"});
    if (out.status!==0) throw new Error("Lua project listing failed: "+out.stderr);
    return new Map(out.stdout.trim().split(/\r?\n/).map(line=>line.split("\t")));
}

function generate() {
    const inventory=JSON.parse(fs.readFileSync(path.join(ROOT,"docs/reference/inventory.json"),"utf8"));
    const source=inventory.sources["projects.js"];
    const byName=new Map(source.projects.map(p=>[p.name,p]));
    const ported=portedProjects();
    const rows=source.project_registration_order.map((name,index)=>{
        const project=byName.get(name);
        let status;
        if (ported.has(name)) {
            const stop=ported.get(name);
            status=stop ? `trigger and eligibility; purchase stops (${stop})` : "trigger, eligibility and purchase effect";
        } else {
            status="later slice: its trigger needs the endings";
        }
        return `| ${index+1} | ${name} | ${project.fields.id.initial} | ${project.line} | ${status} |`;
    });
    const counted=[...ported.values()];
    return [
        "# Project traceability",
        "",
        "Generated by tests/reference/project_checklist.cjs from",
        "[inventory.json](inventory.json) and Sim/Projects.lua; do not edit by hand.",
        "workshop.test.cjs checks that this file is current.",
        "",
        `All three phases and the endings port ${counted.filter(s=>!s).length} purchase effects and`,
        `${counted.filter(s=>s).length} explicit purchase stops. The restarts (the prestige routes and Quantum`,
        `Temporal Reversion) end the company; the host starts the next one (#23).`,
        "",
        "| # | Project | Button | projects.js line | Port |",
        "| ---: | --- | --- | ---: | --- |",
        ...rows,
        "",
    ].join("\n");
}
module.exports={generate,OUTPUT};

if (require.main===module) {
    const text=generate();
    if (process.argv.includes("--write")) fs.writeFileSync(OUTPUT,text);
    else process.stdout.write(text);
}
