"""Generate UI/ProjectText.lua: each project's Time Is Money title (plan Appendix A)
and its reference price tag (the pinned projects.js), in reference declaration order.

Run after `python Tools/paperclips_reference.py fetch`:
    python Tools/make_project_text.py          # rewrite UI/ProjectText.lua
    python Tools/make_project_text.py --check  # fail if it is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / "docs" / "plan" / "Time-Is-Money-Original-Plan.md"
PROJECTS = ROOT / ".tmp-paperclips" / "projects.js"
OUT = ROOT / "UI" / "ProjectText.lua"


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build():
    plan = PLAN.read_text(encoding="utf-8")
    appendix = plan.split("## Appendix A", 1)[1].split("\n## ", 1)[0]
    titles = {name: (title, purpose) for name, title, purpose in
              re.findall(r"^\| `(project\w+)` \| ([^|]+?) \| ([^|]+?) \|", appendix, re.M)}
    source = PROJECTS.read_text(encoding="utf-8")
    rows = []
    for name, body in re.findall(r"^var (project\w+) = \{(.*?)^\}", source, re.M | re.S):
        if name not in titles:
            raise SystemExit(f"{name} has no title in plan Appendix A")
        tag = re.search(r'^\s*priceTag: (.*),\s*$', body, re.M).group(1)
        # Literal tags are kept; computed ones (four projects) are rebuilt by the UI.
        literal = re.fullmatch(r'"([^"]*)"', tag)
        rows.append((name, *titles[name], literal.group(1) if literal else None))
    if len(rows) != len(titles):
        missing = sorted(set(titles) - {r[0] for r in rows})
        raise SystemExit(f"plan titles without a reference project: {missing}")
    lines = [
        "-- Generated by Tools/make_project_text.py: do not edit.",
        "-- Titles and purposes: docs/plan/Time-Is-Money-Original-Plan.md Appendix A. Price tags: the",
        "-- pinned reference projects.js (nil where the reference computes the tag).",
        "local _, ns = ...",
        "ns.ProjectText = {",
    ]
    for name, title, purpose, tag in rows:
        tag_lua = lua_string(tag) if tag is not None else "nil"
        lines.append(f"    {name} = {{ title = {lua_string(title)}, priceTag = {tag_lua},")
        lines.append(f"        purpose = {lua_string(purpose)} }},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def rows_count(text):
    return [line for line in text.splitlines() if "title =" in line]


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            raise SystemExit("UI/ProjectText.lua is out of date: run python Tools/make_project_text.py")
        print("UI/ProjectText.lua matches the plan and the pinned reference")
    else:
        OUT.parent.mkdir(exist_ok=True)
        OUT.write_bytes(text.encode("utf-8"))
        print(f"wrote {OUT.relative_to(ROOT)} ({len(rows_count(text))} projects)")
